# fly.toml app configuration file generated for sketchhub on 2025-07-21T11:31:35+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sketchhub'
primary_region = 'bom'

[build.args]
NEXT_PUBLIC_BACKEND_URL = "https://http-backend-app.fly.dev/v1"
NEXT_PUBLIC_WsURL = "ws://localhost:8080"


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
