name : DEPLOY ws backend to fly.io

on : 
    push : 
        branches : 
            - dev
            - main
        paths : 
            - 'server/database/**'
            - 'server/ws-backend/**'

jobs : 
    deploy : 
        name : Deloy on fly.io
        runs-on : ubuntu-latest

        steps : 
            - name : Checkout code
              uses : actions/checkout@v3

            - name : set up Node.js
              uses : actions/setup-node@v4
              with : 
                node-version : 20
            - name : Install Fly.io CLI
              uses : superfly/flyctl-actions/setup-flyctl@master

            - name : Deploy ws backend to Fly.io
              working-directory : ./server
              run : flyclt deploy --config fly.ws.toml --remote-only
              env : 
                FLY_API_TOKEN : ${{ secrets.FLY_API_TOKEN }}