name: DEPLOY http backend to fly.io

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'server/database/**'
      - 'server/zod-validation/**'
      - 'server/http-backend/**'

jobs:
  test-and-deploy:
    name: Test & Deploy HTTP Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        working-directory: ./server
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        working-directory: ./server
        run: pnpm --filter database exec prisma generate

      - name: Run Unit Tests
        working-directory: ./server
        run: pnpm --filter zod-validation test

      - name: Run Type Checks
        working-directory: ./server
        run: pnpm --filter http-backend exec tsc --noEmit

      - name: Install Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy http backend to Fly.io
        working-directory: ./server
        run: flyctl deploy --config fly.http.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}